dist: bionic
language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgtk-3-dev

install:
  - pip install -r requirements.txt

script:
  - nosetests
