dist: bionic
language: python

python:
  - "3.6"
  - "3.7"

install:
  - sudo apt-get update
  - sudo apt-get install -y libgtk-3-dev python-wxgtk4.0
  - pip install -r requirements-ubuntu.txt

script:
  - nosetests
